### ISSUE TITLE
Code for ListOps and L2X

### ISSUE THREAD

**Issue by chijames** [choidami/sst#2]
Hi,

Thanks for sharing the code! It seems that the other two experiments are not released in this repo. (Please correct me if I am wrong!) Are you able to share them also?

Thanks!

**Comment by mbp28** [comment]
Hello!

Thanks for your interest. 
Currently, we are not planning to release our code for these experiments, as we mainly relied on existing code bases on GitHub to implement these experiments. In particular, 

https://github.com/NYU-MLL/spinn/tree/listops-release
https://github.com/ermongroup/subsets

I hope you find these useful. 
Best wishes, 
Max
